map_type: costmap

obstacle_range: 2.5
raytrace_range: 5.0
robot_radius: 0.5
inflation_radius: 0.4
transform_tolerance: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor : {sensor_frame: hokuyo_link, data_type: LaserScan, topic: gara/scan, marking: true, clearing: true}





