map_type: costmap
obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.5
inflation_radius: 1.75
cost_scaling_factor: 2.58
transform_tolerance: 0.5
track_unknown_space: true
observation_sources: laser_scan_sensor
laser_scan_sensor : {sensor_frame: hokuyo_link, data_type: LaserScan, topic: gara/scan, marking: true, clearing: true, min_obstacle_height : 0.0}






