local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 1
   publish_frequency: 1
   static_map: false
   rolling_window: true
   width: 6 
   height: 6
   resolution: 0.02

