DWAPlannerROS:

  ######## Robot configuration parameters

  #The x acceleration limit of the robot in meters/sec^2
  acc_lim_x: 0.38
  #The rotational acceleration limit of the robot in radians/sec^2
  acc_lim_th: 0.84
  #The y acceleration limit of the robot in meters/sec^2
  acc_lim_y: 0.0

  #The absolute value of the maximum translational velocity for the robot in m/s
  max_vel_trans: 0.7
  #The absolute value of the minimum translational velocity for the robot in m/s
  min_vel_trans: 0.2
  #The maximum x velocity for the robot in m/s.
  max_vel_x: 0.7
  #The minimum x velocity for the robot in m/s, negative for backwards motion.
  min_vel_x: 0.2
  #The maximum y velocity for the robot in m/s
  max_vel_y: 0.0
  #The maximum y velocity for the robot in m/s
  min_vel_y: 0.0
  #The absolute value of the maximum rotational velocity for the robot in rad/s
  max_vel_theta: 1.3
  #The absolute value of the minimum rotational velocity for the robot in rad/s
  min_vel_theta: 0.3


  ######## Goal Tolerance parameters

  #The tolerance in meters for the controller in the x & y distance when achieving a goal
  xy_goal_tolerance: 0.2
  #The tolerance in radians for the controller in yaw/rotation when achieving its goal
  yaw_goal_tolerance: 0.1
  #If goal tolerance is latched, if the robot ever reaches the goal xy location it will 
  #simply rotate in place, even if it ends up outside the goal tolerance while it is doing so
  latch_xy_goal_tolerance: true
  
  ######## Forward Simulation parameters

  #The amount of time to forward-simulate trajectories in seconds
  sim_time: 2.0
  #The step size, in meters, to take between points on a given trajectory
  sim_granularity: 0.025
  #The number of samples to use when exploring the x velocity space
  vx_samples: 10
  #The number of samples to use when exploring the y velocity space
  vy_samples: 0
  #The number of samples to use when exploring the theta velocity space
  vth_samples: 20

  ######## Trajectory Scoring Parameters

  #The absolute value of the velocity at which to start scaling the robot's footprint, in m/s
  scaling_speed: 0.25
  #The maximum factor to scale the robot's footprint by
  max_scaling_factor: 0.2


  ######## Oscillation Prevention Parameters

  #How far the robot must travel in meters before oscillation flags are reset  
  oscillation_reset_dist: 0.05


  ######## Global Plan  parameters

  #Defines whether or not to eat up the plan as the robot moves 
  #along the path. If set to true, points will fall off the end 
  #of the plan once the robot moves 1 meter past them.
  prune_plan: false

  
  path_distance_bias: 42.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
