local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 1
   publish_frequency: 2
   static_map: false
   rolling_window: true
   width: 10 
   height: 10
   resolution: 0.05

