<?xml version="1.0"?>

<robot name="gara" xmlns:xacro="http://www.ros.org/wiki/xacro">


	<xacro:include filename="$(find gara_simulation)/urdf/macros.xacro" />

	<xacro:include filename="$(find gara_simulation)/urdf/gara.gazebo" />

	<xacro:include filename="$(find gara_simulation)/urdf/gara_dimensions.xacro" />

	<!-- Base Link -->
	<link name="base_link"></link>

	<!--Robot chassis Link 	-->
	<link name="chassis">

  		<visual>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0" />
			<geometry>
		  	<cylinder length="${chassisWidth}" radius="${chassisRadius}"/>
			</geometry>
  		</visual>

		<collision>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0" />
  			<geometry>
    			<cylinder length="${chassisWidth}" radius="${chassisRadius}"/>
  			</geometry>
		</collision>

		<inertial>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0" />
  			<mass value="${chassisMass}"/>
			<cylinder_inertia 
				m="${chassisMass}" 
				r="${chassisRadius}" 
				h="${chassisWidth}"/>
		</inertial>

	</link>

	<!--Robot chassis Joint -->    
  	<joint name="base_link_joint" type="fixed">

		<origin xyz="0 0 0" rpy="0 0 0" />
    	<parent link="base_link"/>
    	<child link="chassis" />	

  	</joint>

	<!--Caster Link -->
	<link name="center_wheel">

		<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<sphere radius="${casterRadius}"/>
				</geometry>
		</visual>

		<collision>
 			<geometry>
    			<sphere radius="${casterRadius}"/>
 			</geometry>
		</collision>

		<inertial>
 			<mass value="${casterMass}"/>
			<sphere_inertia 
				m="${casterMass}" 
				r="${casterRadius}"/>
		</inertial>

	</link>
	
	<!--Caster Joint -->
	<joint name="center_wheel_joint" type="fixed">

		<origin xyz="0.14 0 ${casterRadius}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="center_wheel"/>	

	</joint>
	
	<!-- Left Wheel Link  	-->
	<link name='left_wheel'>

		<visual>
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
			</geometry>
		</visual>

		<collision name='collision'>
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
			</geometry>
		</collision>

		<inertial>
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<mass value="${wheelMass}"/>
			<cylinder_inertia 
				m="${wheelMass}" 
				r="${wheelRadius}" 
				h="${wheelWidth}"/>
		</inertial>

	</link>

	<!-- Left Wheel Joint --> 
	<joint name="left_wheel_hinge" type="continuous">

		<axis xyz="0 1 0" rpy="0 0 0"/>
		<origin xyz="-0.182 0.285 ${wheelRadius}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="left_wheel"/>
		
		<limit effort="10000.0" velocity="10000.0"/>
      		
	</joint>

	<!-- Right Wheel Link -->
	<link name='right_wheel'>

		<visual >
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
			</geometry>
		</visual>

		<collision name='collision'>
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelWidth}"/>
			</geometry>
		</collision>

		<inertial>
			<origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
			<mass value="${wheelMass}"/>
			<cylinder_inertia 
				m="${wheelMass}" 
				r="${wheelRadius}" 
				h="${wheelWidth}"/>
		</inertial>

	</link>

	<!-- Right Wheel Joint -->
	<joint name="right_wheel_hinge" type="continuous" >

		<axis xyz="0 1 0" rpy="0 0 0"/>	
		<origin xyz="-0.182 -0.285 ${wheelRadius}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="right_wheel"/>

		<limit effort="10000.0" velocity="10000.0"/>
		
	</joint>

	<!-- Mast Link -->
	<link name='mast'>

		<visual name='mast_visual'>
			<origin xyz="0.0 0 0.55" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.02" length="1.1"/>
			</geometry>
		</visual>

		<collision name='collision'>
			<origin xyz="0.0 0 0.55" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.02" length="1.1"/>
			</geometry>
		</collision>

		<inertial>
			<origin xyz="0.0 0 0.55" rpy="0 0 0"/>
			<mass value="0.1"/>
			<cylinder_inertia 
				m="0.1" 
				r="0.02" 
				h="1.1"/>
		</inertial>

	</link>
	
	<!-- Mast Joint -->
	<joint name="mast_hinge" type="fixed" >

		<origin xyz="0 0 ${wheelRadius+0.009}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="mast"/>

	</joint>
	
	<!-- Camera Link -->
	<link name="camera_link">

		<visual>
  			<geometry>
					<box size="0.025 0.085 0.01"/>
  			</geometry>     
		</visual>

		<collision>
  			<origin xyz="0 0 0" rpy="0 0 0"/>
  			<geometry>
				<box size="0.025 0.085 0.01"/>
  			</geometry>
		</collision>

		<inertial>
			<mass value="0.1" />
			<box_inertia 
				m="0.1" 
				x="0.025" 
				y="0.085"
				z="0.01"/>
		</inertial>

	</link>
	
	<!-- Camera Joint -->
	<joint name="camera_joint" type="fixed">

		<origin xyz="0.09 0 0.85" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="camera_link"/>

	</joint>

	<!-- Camera RGBD Link 	-->
	<link name='camera_rgbd_frame'></link>

	<!-- Camera RGBD Joint -->
	<joint name="camera_rgbd_joint" type="fixed" >

		<origin xyz="0 0 0" rpy="-1.5707963267948966 0 -1.5707963267948966"/>
  		<parent link="camera_link"/>
    	<child link="camera_rgbd_frame"/>

  	</joint> 	

	<!-- Hokuyo Laser Link 	-->
	<link name="hokuyo_link">

  		<visual>
    			<origin xyz="0 0 0" rpy="0 0 0"/>
    			<geometry>
      			<mesh filename="package://gara_simulation/meshes/hokuyo.dae"/>
    			</geometry>
  		</visual>

  		<collision>
    			<geometry>
      			<box size="0.1 0.1 0.1"/>
    			</geometry>
  		</collision>

  		<inertial>
		  	<mass value="0.1" />
			<box_inertia 
				m="0.1" 
				x="0.1" 
				y="0.1"
				z="0.1"/>
  		</inertial>

	</link>

 	<!-- Hokuyo Laser Joint -->
	<joint name="hokuyo_joint" type="fixed">

    	<axis xyz="0 1 0" />
  		<origin xyz="0 0 1.1" rpy="0 0 0"/>
  		<parent link="chassis"/>
  		<child link="hokuyo_link"/>

  	</joint>

	<!-- Hokuyo Laser Link -->
	<link name="imu_link">

		<visual>
			<geometry>
				<box size="0.01 0.01 0.01"/>
			</geometry>
		</visual>

		<collision>
  			<geometry>
    			<box size="0.01 0.01 0.01"/>
  			</geometry>
		</collision>

		<inertial>
		  	<mass value="0.1" />
			<box_inertia 
				m="0.1" 
				x="0.01" 
				y="0.01"
				z="0.01"/>
		</inertial>

	</link>

 	<!-- IMU Joint 	-->
	<joint name="imu_joint" type="fixed">

		
		<origin xyz="-0.2 0 ${wheelRadius}" rpy="0 0 0"/>
		<parent link="chassis"/>
		<child link="imu_link"/>

  	</joint>
  
</robot>
